name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ybiquitous/.github/.github/workflows/nodejs-release-reusable.yml@11134ce0efbe36bdd758ab41e38fd8e05bf0a10d # v3.3.0
    with:
      create-release: false
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      id-token: write
