name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/nodejs-release-reusable.yml
    with:
      create-release: false
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
