name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ybiquitous/.github/.github/workflows/nodejs-release-reusable.yml@cdefa43486604b3aae79e9d1db24b670475f2c92 # v3.2.0
    with:
      create-release: false
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      id-token: write
