name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ybiquitous/.github/.github/workflows/nodejs-release-reusable.yml@46e5ee1d74cc40a0448a372e22cf3e5852efd59a # v3.0.2
    with:
      create-release: false
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      id-token: write
