name: Test

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ["18", "20", "22", "24"]
    uses: ybiquitous/.github/.github/workflows/nodejs-test-reusable.yml@11134ce0efbe36bdd758ab41e38fd8e05bf0a10d # v3.3.0
    with:
      node-version: ${{ matrix.node-version }}
    permissions:
      contents: read

  lint:
    uses: ybiquitous/.github/.github/workflows/nodejs-lint-reusable.yml@11134ce0efbe36bdd758ab41e38fd8e05bf0a10d # v3.3.0
    permissions:
      contents: read
